apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to Nginx</title>
    </head>
    <body>
    <h1>Hello, Tommy Ho <> Phylax</h1>
    </body>
    </html>

